[package]
name = "dsnfs"
version = "0.1.0"
edition = "2021"
description = "Dead Simple Network File Sender (wherein the simplicity goes both ways - implementation and usability)"

[dependencies]
clap = "^2.33.3"
